### ISSUE TITLE
withPaginationType not displaying pagination

### ISSUE THREAD

**Issue by KaustubhSrivastava** [l-lin/angular-datatables#1084]
I am trying to use withPaginationType ('full_numbers') but its not displaying pagination content.
On inspecting I could see thats because of 
```css
.dataTables_info, .dataTables_paginate, .dataTables_length, .dataTables_filter, .dt-loading {
     display: none !important; 
}
``` 
On deselecting display: none it shows the pagination as expected.

Please find below related js code.
```js
vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
            return adminService.listOfUsers(); })
        .withDataProp('data')
        .withPaginationType('full_numbers');
vm.dtColumns = [
        DTColumnBuilder.newColumn('username').withTitle('User Name'),
        DTColumnBuilder.newColumn('firstName').withTitle('First name'),
        DTColumnBuilder.newColumn('lastName').withTitle('Last name'),
        DTColumnBuilder.newColumn('email').withTitle('Email'),
        DTColumnBuilder.newColumn('cellPhone').withTitle('Mobile Phone(SMS)'),
        DTColumnBuilder.newColumn('active').withTitle('Active'),
    ];
```
and html
```html
<table datatable="" dt-options="vm.dtOptions" dt-columns="vm.dtColumns" class="row-border hover">
```
Kindly provide some help or let me know if you need any other information.

Thanks,
Kaustubh
