### ISSUE TITLE
Process Message Dialog does not show if WithBootstrap() is added

### ISSUE THREAD

**Issue by jandayanan** [l-lin/angular-datatables#410]
Hi.

What could possibly be the issue when the processing dialog of the datatable/tabletools is not shown?

See here:

In the fiddle below, the one without .withbootstrap() call, you can see that if you click print in tabletools, there is an information dialog telling you that this table is printed and so on:
http://jsfiddle.net/qu4a7j24/3/

While on this other fiddle, one with the .withbootstrap() call, you can't see any process message for the table.
http://jsfiddle.net/qu4a7j24/2/

What could possibly be the culprit?

Thanks

NOTE: I want to use bootstrap in this case.

**Comment by l-lin** [comment]
The message displayed is the following:
```html
<div class="DTTT_print_info modal">
    <h6>Print view</h6>
    <p>
        Please use your browser's print function to print this table.
        Press escape when finished.
    </p>
</div>
```
Except that in the bootstrap CSS file, there is something like this:
```css
.modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1040;
  display: none; /* HERE IS THE PROBLEM */
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
  outline: 0;
}
```
So you can add the following CSS property to make it work:
```css
.DTTT_print_info.modal {
    display: block;
}
```
